Repository COS301-SE-2024/Query-Builder, pull requests merged in 2024-06, with the labels that each got.

#60 Dev
  query-builder-docs/docs/requirements-specification/architectural-requirements/_category_.json
  query-builder-docs/docs/requirements-specification/architectural-requirements/architectural-patterns.md
  query-builder-docs/docs/requirements-specification/architectural-requirements/constraints.md
  query-builder-docs/docs/requirements-specification/architectural-requirements/design-patterns.md
  query-builder-docs/docs/requirements-specification/architectural-requirements/quality-requirements.md
  query-builder-docs/docs/requirements-specification/class-diagram.md
  query-builder-docs/docs/requirements-specification/functional-requirements.md
  query-builder-docs/docs/requirements-specification/introduction.md
  query-builder-docs/docs/requirements-specification/service-contracts.md
  query-builder-docs/docs/requirements-specification/technology-requirements.md
  query-builder-docs/docs/requirements-specification/use-case-diagrams.md
  query-builder-docs/docs/requirements-specification/user-stories.md
  query-builder-docs/static/img/DatabaseSystemManager.drawio
  query-builder-docs/static/img/DatabaseSystemManagerDark.png
  query-builder-docs/static/img/DatabaseSystemManagerLight.png
  query-builder-docs/static/img/OrganisationManagement.drawio
  query-builder-docs/static/img/OrganisationManagementDark.png
  query-builder-docs/static/img/OrganisationManagementLight.png
  query-builder-docs/static/img/QBEEBridge.png
  query-builder-docs/static/img/QBEEMediator.png
  query-builder-docs/static/img/QBEESingleton.png
  query-builder-docs/static/img/QueryBuilder.drawio
  query-builder-docs/static/img/QueryBuilderDark.png
  query-builder-docs/static/img/QueryBuilderLight.png
  query-builder-docs/static/img/Reporting.drawio
  query-builder-docs/static/img/ReportingDark.png
  query-builder-docs/static/img/ReportingLight.png
  query-builder-docs/static/img/UserAuthentication.drawio
  query-builder-docs/static/img/UserAuthenticationDark.png
  query-builder-docs/static/img/UserAuthenticationLight.png
  query-builder-docs/static/img/UserManagement.drawio
  query-builder-docs/static/img/UserManagementDark.png
  query-builder-docs/static/img/UserManagementLight.png
Labels: documentation, enhancement, task

#68 Created and added LICENSE.txt
  LICENSE.txt
Labels: documentation

#77 feat(devops): added testing, linting, deployment, building and code coverage
  .github/workflows/app-deploy.yaml
  .github/workflows/app-lint.yaml
  .github/workflows/app-test.yaml
  .github/workflows/docs-deploy.yaml
  .github/workflows/docs-lint.yaml
  .github/workflows/docs-test-deploy.yaml
  .github/workflows/tests-code-coverage.yaml
  .nvmrc
  package.json
  query-builder-app/.prettierrc.json
  query-builder-app/eslint.config.mjs
  query-builder-app/package.json
  query-builder-app/pnpm-lock.yaml
  query-builder-app/vitest.config.ts
Labels: enhancement, task

#79 Feature/code coverage badges
  LICENSE.txt
  README.md
Labels: documentation, enhancement, task

#70 DatabaseConnectionModal basic frontend
  query-builder-app/.npmrc
  query-builder-app/package.json
  query-builder-app/pnpm-lock.yaml
  query-builder-app/src/app/layout.tsx
  query-builder-app/src/components/DatabaseConnectionModal/DatabaseConnectionModal.tsx
  query-builder-app/src/components/stories/DatabaseConnectionModal.stories.tsx
  query-builder-backend/src/connect/connect.controller.ts
  query-builder-backend/src/connection-manager/connection-manager.service.ts
  query-builder-backend/src/main.ts
Labels: documentation, enhancement, task

#93 Update README.md
  README.md
Labels: documentation

#118 Feature/readme update
  README.md
  package.json
Labels: documentation

#125 Feature/login frontend
  package-lock.json
  package.json
  query-builder-app/.gitignore
  query-builder-app/package.json
  query-builder-app/pnpm-lock.yaml
  query-builder-app/src/components/Authentication/Authentication.css
  query-builder-app/src/components/Authentication/Authentication.tsx
  query-builder-app/src/components/Authentication/EyeFilledIcon.tsx
  query-builder-app/src/components/Authentication/EyeSlashFilledIcon.tsx
  query-builder-app/src/components/Form/Form.tsx
  query-builder-app/src/components/UserSettings/UserSettings.tsx
  query-builder-app/src/components/stories/Authentication.stories.tsx
  query-builder-app/src/components/stories/UserSettings.stories.tsx
Labels: enhancement, task

#129 Basic signed-in home page
  query-builder-app/src/app/globals.css
  query-builder-app/src/components/DatabaseConnectionModal/DatabaseConnectionModal.tsx
  query-builder-app/src/components/SignedInHomePage/DeleteIcon.tsx
  query-builder-app/src/components/SignedInHomePage/EditIcon.tsx
  query-builder-app/src/components/SignedInHomePage/SignedInHomePage.tsx
  query-builder-app/src/components/stories/SignedInHomePage.stories.tsx
  query-builder-backend/src/connect/connect.controller.ts
Labels: enhancement, task

#148 Docs for Frotend (Please dont delete branch after merge)
  query-builder-app/pnpm-lock.yaml
  query-builder-app/src/components/UserSettings/UserSettings.tsx
  query-builder-docs/docs/architectural-requirements/technology-choices.md
Labels: documentation, enhancement, task

#157 side bar added (please don't delete branch)
  query-builder-app/pnpm-lock.yaml
  query-builder-app/src/app/[query-builder]/page.tsx
  query-builder-app/src/app/globals.css
  query-builder-app/src/app/layout.tsx
  query-builder-app/src/app/page.tsx
  query-builder-app/src/components/Form/Form.tsx
  query-builder-app/src/components/SideBar/Logo.tsx
  query-builder-app/src/components/SideBar/SideBar.css
  query-builder-app/src/components/SideBar/SideBar.tsx
  query-builder-app/src/components/SignedInHomePage/SignedInHomePage.tsx
  query-builder-app/src/components/UserSettings/UserSettings.tsx
  query-builder-app/src/components/stories/SideBar.stories.tsx
  query-builder-backend/pnpm-lock.yaml
  query-builder-backend/src/app.module.ts
Labels: enhancement, task

#159 sidebar and usermanagement
  query-builder-app/src/app/settings/page.tsx
  query-builder-app/src/components/SideBar/SideBar.tsx
  query-builder-app/src/components/UserSettings/UserSettings.tsx
Labels: enhancement, task
